# Generated by Django 4.2 on 2023-05-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Тема')),
                ('content', models.TextField(verbose_name='Текст')),
                ('criticalness', models.SmallIntegerField(choices=[(1, 'Низкая'), (2, 'Средняя'), (3, 'Высокая'), (4, 'Критичная')], default=2, verbose_name='Критичность')),
                ('progress', models.SmallIntegerField(choices=[(1, 'Невозможно выполнить'), (2, 'Принято к рассмотрению'), (3, 'В стадии решения'), (4, 'Успешно решено')], default=2, verbose_name='Статус заявки')),
                ('published', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время создания')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='ФИО')),
                ('password', models.CharField(max_length=50, verbose_name='Пароль')),
                ('telnumber', models.IntegerField(max_length=11, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='адрес почты')),
                ('userclass', models.SmallIntegerField(choices=[(1, 'Клиент'), (2, 'Админ')], default=1, verbose_name='Класс пользователя')),
            ],
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
