# Generated by Django 4.2 on 2023-05-18 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0003_alter_ticket_criticalness_alter_ticket_progress_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
