# Generated by Django 4.2 on 2023-05-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0005_ticket_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-published'], 'permissions': [('view_all_tickets', 'Can view all tickets')], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
