# Generated by Django 4.2 on 2023-05-20 13:07

import desk.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('desk', '0007_ticket_technician_alter_ticket_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='chat',
            field=models.JSONField(blank=True, default=list, verbose_name='Чат'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='progress',
            field=models.CharField(choices=[('Невозможно выполнить', 'Невозможно выполнить'), ('Принято к рассмотрению', 'Принято к рассмотрению'), ('В стадии решения', 'В стадии решения'), ('Успешно решено', 'Успешно решено'), ('Закрыто', 'Закрыто')], default='Принято к рассмотрению', max_length=25, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='technician',
            field=models.ForeignKey(blank=True, default=desk.models.get_default_technician, limit_choices_to={'groups__name': 'Техник'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
    ]
