# Generated by Django 4.2 on 2023-08-22 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0011_alter_ticket_technician_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
