# Generated by Django 4.2 on 2023-08-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0014_alter_userprofile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('открыта', 'Открыта'), ('закрыта', 'Закрыта')], default='открыта', max_length=10, verbose_name='Открытость заявки'),
        ),
    ]
